"""
Export Module
Handles exporting canvas data to various formats (PNG, TXT, etc.).
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Dict
from collections import defaultdict

from PIL import Image

from app.core.renderer import BlockRenderer
from app.minecraft.texturepack.models import BlockTexture


class Exporter:
    """Handles exporting canvas data to various formats."""
    
    @staticmethod
    def export_image(block_grid: List[List[BlockTexture]], output_path: Path) -> None:
        """
        Exports block grid as PNG image.
        
        Args:
            block_grid: 2D grid of BlockTexture
            output_path: Path to save PNG file
        """
        if not block_grid or not block_grid[0]:
            raise ValueError("Empty block grid")
        
        renderer = BlockRenderer(block_size=16)
        renderer.render(block_grid, output_path=output_path)
    
    @staticmethod
    def export_block_list(block_stats: Dict, output_path: Path) -> None:
        """
        Exports block statistics to text file.
        
        Args:
            block_stats: Dictionary with block statistics
            output_path: Path to save TXT file
        """
        if not block_stats:
            raise ValueError("No block statistics to export")
        
        # Calculate totals
        total_blocks = sum(stats['total'] for stats in block_stats.values())
        unique_types = len(block_stats)
        
        # Generate text content
        lines = []
        lines.append("="*60)
        lines.append("MINECRAFT PIXEL ART - BLOCK LIST")
        lines.append("="*60)
        lines.append("")
        lines.append(f"Total Blocks: {total_blocks:,}")
        lines.append(f"Unique Types: {unique_types}")
        lines.append("")
        lines.append("="*60)
        lines.append("BLOCKS BY QUANTITY (Most to Least)")
        lines.append("="*60)
        lines.append("")
        
        # Sort blocks by count (descending)
        sorted_blocks = sorted(block_stats.items(), key=lambda x: x[1]['total'], reverse=True)
        
        for base_name, stats in sorted_blocks:
            # Main block line
            lines.append(f"{base_name}: {stats['total']} blocks")
            
            # If multiple variants, show breakdown
            if len(stats['variants']) > 1:
                for variant, count in sorted(stats['variants'].items(), key=lambda x: x[1], reverse=True):
                    lines.append(f"  • {variant}: {count}")
                lines.append("")  # Empty line after multi-variant blocks
        
        lines.append("")
        lines.append("="*60)
        lines.append("Generated by Minepixel Editor")
        lines.append("="*60)
        
        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
    
    @staticmethod
    def analyze_grid_blocks(block_grid: List[List[BlockTexture]], 
                           get_base_block_name_func, 
                           get_block_variant_func) -> Dict:
        """
        Analyzes block grid and returns statistics.
        
        Args:
            block_grid: 2D grid of BlockTexture
            get_base_block_name_func: Function to get base name from block_id
            get_block_variant_func: Function to get variant from block_id
        
        Returns:
            Dictionary with block statistics
        """
        if not block_grid:
            return {}
        
        # Count blocks by base name and variant
        block_counts = defaultdict(lambda: {
            'total': 0,
            'variants': defaultdict(int),
            'blocks': {}  # variant -> BlockTexture
        })
        
        for row in block_grid:
            for block in row:
                if block:
                    base_name = get_base_block_name_func(block.block_id)
                    variant = get_block_variant_func(block.block_id)
                    
                    block_counts[base_name]['total'] += 1
                    block_counts[base_name]['variants'][variant] += 1
                    
                    # Store one example of each variant
                    if variant not in block_counts[base_name]['blocks']:
                        block_counts[base_name]['blocks'][variant] = block
        
        return dict(block_counts)
